ADDITIONAL_INPUT_PREFIX = "additional_input_"

ADDITIONAL_INPUT_EGOVEHICLE = ADDITIONAL_INPUT_PREFIX + "egovehicle"
ADDITIONAL_INPUT_EGOVEHICLE_MANEUVER = ADDITIONAL_INPUT_EGOVEHICLE + "_maneuver"
ADDITIONAL_INPUT_EGOVEHICLE_LANE_CHANGE = ADDITIONAL_INPUT_EGOVEHICLE + "_lane_change"
ADDITIONAL_INPUT_EGOVEHICLE_LANE_INDEX = ADDITIONAL_INPUT_EGOVEHICLE + "_lane_index"

# Waymo specific, objects_of_interest
ADDITIONAL_INPUT_INTERACTIVE = ADDITIONAL_INPUT_PREFIX + "interactive"
# Is relevant agents
ADDITIONAL_INPUT_RELEVANT_PEDESTRIAN = ADDITIONAL_INPUT_PREFIX + "relevant_pedestrian"
ADDITIONAL_INPUT_ADDITIONAL_AGENT = ADDITIONAL_INPUT_PREFIX + "additional_agent"
ADDITIONAL_INPUT_KEY_VISUAL_BBOX = ADDITIONAL_INPUT_PREFIX + "visual_bbox"

ADDITIONAL_INPUT_KEY_TYPE = ADDITIONAL_INPUT_PREFIX + "key_type"
ADDITIONAL_INPUT_KEY_TRI_DOT_ID = ADDITIONAL_INPUT_PREFIX + "key_tri_dot_id"
ADDITIONAL_INPUT_KEY_CAMERA_IMAGE = ADDITIONAL_INPUT_PREFIX + "key_camera_image"
ADDITIONAL_INPUT_KEY_DOT_ID = ADDITIONAL_INPUT_PREFIX + "key_tri_dot_id"
